server:
  port: 8083

spring:
  main:allow-bean-definition-overriding: true
  profiles:
    active: local
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:oracle:thin:@//119.205.217.251:1521/orcl
    username: ill
    password: ill
  jpa:
    hibernate:
      #      절대로 건들지 안됌!!!!
      ddl-auto: none
    properties:
      hibernate:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  #        show_sql: true
  #        format_sql: true
# p6spy 설정
decorator.datasource.p6spy:
  enable-logging: true
  multiline: true
  logging: slf4j

#mybatis 설정
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations: mapper/*.xml




